### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Manawyrm/ATAPIHat-driver#1]
Hello!

I found link to this project from https://hackaday.com/2020/08/10/raspberry-pi-gets-pata-ide-drive-via-gpio-header/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

If your code is based on Linux kernel, then GPLv2 is the best choice, I think.

**Comment by Manawyrm** [comment]
Hello Alexey,

thanks for the reminder to add a license, I forgot to do so :smiley: 
I agree that GPL is a good choice (especially since many of the functions are very similar or even copies of existing GPLv2 linux drivers), I've licensed the code as GPLv2.

**Comment by vazhnov** [comment]
@Manawyrm, thank you!
